# Generated by Django 3.2.9 on 2021-12-09 14:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_ngo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cred_points',
            field=models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
