# Generated by Django 3.2.9 on 2021-12-02 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NGO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField()),
                ('links', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='images')),
                ('helpline_no', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField()),
                ('venue', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('ngo_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ngo.ngo')),
            ],
        ),
    ]
