# Generated by Django 3.2.9 on 2021-12-04 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
